CLASS zcl_lab_12_linux_lm01 DEFINITION INHERITING FROM zcl_lab_11_system_lm01
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_lm01 IMPLEMENTATION.
ENDCLASS.
