CLASS zcl_lab_19_lion_lm01 DEFINITION INHERITING FROM zcl_lab_18_animal_lm01
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_19_lion_lm01 IMPLEMENTATION.
  METHOD walk.
    rv_walk = |The lion walks|.
  ENDMETHOD.

ENDCLASS.
