CLASS zcl_06_storage_lm01 DEFINITION INHERITING FROM zcl_05_plant_lm01
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_storage_lm01 IMPLEMENTATION.
ENDCLASS.
