 CLASS zcl_lab_21_classroom_lm01 DEFINITION
  PUBLIC
  CREATE PROTECTED .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_21_classroom_lm01 IMPLEMENTATION.
ENDCLASS.
