CLASS zcl_08_lion_lm01 DEFINITION INHERITING FROM zcl_07_animall_lm01
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_08_lion_lm01 IMPLEMENTATION.
  METHOD walk.
    rv_walk = 'The Lion Walks'.

  ENDMETHOD.

ENDCLASS.
